FROM rust:1.42.0-buster as builder

# Set the working directory.
# RUN apt-get install cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz && tar -zxvf cmake-3.15.2.tar.gz && cd cmake-3.15.2 && ./bootstrap && make && sudo make install
WORKDIR /usr/src/
COPY . .
# clone one release tag from github 
# RUN git clone --branch v0.5.1 https://github.com/Conflux-Chain/conflux-rust
# RUN env
# cargo registry
RUN echo "[source.crates-io]\n \
registry = 'https://github.com/rust-lang/crates.io-index'\n \
replace-with = 'ustc'\n \
[source.ustc]\n \
registry = 'git://mirrors.ustc.edu.cn/crates.io-index'" > /usr/local/cargo/config
# RUN cat /usr/local/cargo/config
RUN cargo clean
RUN cargo build --release

# second stage
FROM alpine:latest
WORKDIR /root

# copy the binary and config file template
COPY --from=builder /usr/src/conflux-rust/target/release/conflux .
COPY --from=builder /usr/src/conflux-rust/run .
RUN cd /root/run
EXPOSE 12535 12536 12537 12538 12539 32323 32525

CMD [ "/root/conflux", "--config", "./default.toml" ]